import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "public/**",
      "prisma/migrations/**",
      "test-results/**",
      "playwright-report/**",
      // Regenerated by `next build`; its triple-slash refs aren't ours to fix.
      "next-env.d.ts",
    ],
  },
  {
    rules: {
      // Prisma's generated `_count`/`_sum` shapes and intentional throwaways.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", ignoreRestSiblings: true },
      ],
      // `any` is banned, but explicit `unknown` narrowing is the pattern here.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
];

export default config;
